dist: trusty
language: node_js
node_js:
  - "8.12.0"
install: 
  - npm install
  - npm install -g truffle
  - npm install solidity-coverage
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install solc
script: 
  - ./node_modules/.bin/eslint ./test
  - ./node_modules/.bin/solidity-coverage
#  - npm install -g istanbul
#  - istanbul check-coverage --statements 100 --branches 80 --functions 100 --lines 100